### ISSUE TITLE
ALLOW_TOKEN_PARSERS has no effect

### ISSUE THREAD

**Issue by vivazzi** [django-cms/djangocms-text-ckeditor#391]
In docs on page https://github.com/divio/djangocms-text-ckeditor it is said that I can add my ALLOW_TOKEN_PARSERS:

```
And add your class to ALLOW_TOKEN_PARSERS settings:

ALLOW_TOKEN_PARSERS = (
    'mymodule.DonutAttributeParser',
)
```

But in djangocms-text-ckeditor settings.py ALLOW_TOKEN_PARSERS https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/settings.py#L38 is not overridable:

```
ALLOW_TOKEN_PARSERS = (
    'djangocms_text_ckeditor.attribute_parsers.DataAttributeParser',
)
```

**Comment by vThaian** [comment]
@czpython what you think? We should add the possibility to override it?
