### ISSUE TITLE
NoReverseMatch at /admin/cms/page/edit-plugin/1/

### ISSUE THREAD

**Issue by GregoryAveryWeir** [django-cms/djangocms-text-ckeditor#431]
We recently updated from older versions of django-cms and djangocms-text-ckeditor. Now, when trying to edit a CMS placeholder by double-clicking it in Content edit more, we're getting the following error on the AJAX call to pull up the editor:

**NoReverseMatch at /admin/cms/page/edit-plugin/1/**
`Reverse for 'app_list' with arguments '()' and keyword arguments '{u'app_label': 'djangocms_text_ckeditor'}' not found. 1 pattern(s) tried: [u'admin/(?P<app_label>django_comments|auth|updates|filer|cms|tagging|zinnia|sites|djangocms_snippet)/$']`

What could be going on? It looks as if djangocms-text-ckeditor is failing to register itself somehow.

Versions:
Django==1.9.12
django-cms==3.4.3
djangocms-text-ckeditor==3.5.0

**Comment by GregoryAveryWeir** [comment]
We're using django-admin-bootstrap to style our admin, but if we disable it everything works. It's weird, because django-admin-bootstrap is almost entirely just new templates.

**Comment by czpython** [comment]
Hello @GregoryAveryWeir,
Can you confirm the `NoReverseMatch` error is raised by a template?

**Comment by GregoryAveryWeir** [comment]
I can confirm. Django thinks the error is in `djangocms_text_ckeditor/templates/cms/plugins/text_plugin_change_form.html` at line 0, but that template never tries to reverse `app_list`. This suggests the error is in the `change_form_template` or one of its parents.

**Comment by vThaian** [comment]
@GregoryAveryWeir do you have this issue still? Did you try with newest versions maybe?

**Comment by GregoryAveryWeir** [comment]
@vThaian We're holding off on upgrading `djangocms-text-ckeditor` until #474 is resolved, as we use ManifestFilesMixin, but this still occurs with:

Django==1.11.13
django-cms==3.6.0
djangocms-text-ckeditor==3.5.3
bootstrap-admin==0.4.2
