### ISSUE TITLE
links around cmsplugins are removed upon save

### ISSUE THREAD

**Issue by macolo** [django-cms/djangocms-text-ckeditor#434]
When I create a cmsplugin instance in the text editor (for example a bootstrap3 image) and then click on the cursor icon that appears on hover, and then create a normal link (not a cmsplugin link), the link gets correctly created around the image cmsplugin. But upon saving it is stripped away.

I am currently searching for ways to prevent that.

**Comment by vThaian** [comment]
@macolo any updates here? Could you please share more details about versions?
