### ISSUE TITLE
Is the drag & drop of image features still working?

### ISSUE THREAD

**Issue by lazydragon** [django-cms/djangocms-text-ckeditor#435]
Within a text plugin dialog, I can input texts and filer images correctly.

However, drag & drop of images from windows system to the dialog box doesn't have any effect, not even an error thrown on either front end or backend

**Comment by lucashelfs** [comment]
I'm also curious about this. I would like to add images to my articles using only the djangocms-text-ckeditor, unfortunately it seems that it is not possible.

**Comment by czpython** [comment]
Drag & drop is supported by the ckeditor js library but djangocms-text-ckeditor currently does not support this. Adding can image can only be done using the embedded image plugin.

**Comment by Chematronix** [comment]
Drag & Drop or pasting images only works in the Paste from Word dialog for me, though before it worked directly in the editor.  I'm using version 3.2.1.

https://github.com/django-ckeditor/django-ckeditor uses a more up to date version, but you'll lose DjangoCMS/plugin integration.

**Comment by jrief** [comment]
[djangocms-cascade](https://pypi.org/project/djangocms-cascade/) has a plugin which can handle images inside the text editor. It behaves as a normal CMS plugin and uses django-filer as its media store. It is even possible to wrap such an image inside a link element, pointing onto existing CMS pages.

**Comment by Chematronix** [comment]
Nice project @jrief!  But does the plugin actually supports drag & drop or copy/paste?  It's not mentioned in the docs.  Also, does it works in all major browsers?  The lack of Chrome support made me give up on djangocms-text-ckeditor.

**Comment by vThaian** [comment]
@lazydragon did you check cascade plugin as a solution?
