### ISSUE TITLE
Q: access and overwrite htmlWriter?

### ISSUE THREAD

**Issue by creimers** [django-cms/djangocms-text-ckeditor#492]
According to the [ckeditor docs](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_htmlWriter.html#method-setRules), rather fine grained settings can be applied to individual tags that the editor renders (htmlWriter).

Is there a way to access and overwrite these kind of settings in djangocms-text-ckeditor?

**Comment by jrief** [comment]
Could you please be more specific on what you want to achieve. Using the settings variable `CKEDITOR_SETTINGS` it is possible to configure CKEditor quite heavily to your own needs.

**Comment by creimers** [comment]
I can.

I would like to perform the following stunt:

```
// Break line before and after "ul" tags.
writer.setRules( 'ul', {
    breakBeforeOpen: false
    breakAfterOpen: false
} );
```

This is described in the editor's docs [here](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_htmlWriter.html#method-setRules)

**Comment by vThaian** [comment]
@creimers is this issue still present?

**Comment by creimers** [comment]
This is still something I'd be interested in, yes.
