### ISSUE TITLE
ckeditor 5

### ISSUE THREAD

**Issue by Bachstelze** [django-cms/djangocms-text-ckeditor#498]
Are there plans to integrate ckeditor version 5?

**Comment by FinalAngel** [comment]
@Bachstelze we do not have a plan to update to CKEditor 5 currently. It is pretty new and certain features, like custom django CMS plugins, are not easy to be integrated.

We're happy for a pull request integrating CKEditor 5! Though it's sadly not a simple task 🥇

**Comment by pranaysharma** [comment]
@FinalAngel : any suggestions how one can  start

**Comment by jrief** [comment]
@pranaysharma you can have a look at my [attempt to upgrade to CKEditor version 4.13](https://github.com/jrief/djangocms-text-ckeditor/tree/feature/ckeditor-4.13.1). Everything works fine there, except CMS plugin integration. This feature however is ultimatively important for django-CMS.
