### ISSUE TITLE
Problem getting ckeditor's static files when used with a CDN

### ISSUE THREAD

**Issue by arnav13081994** [django-cms/djangocms-text-ckeditor#508]
Hi, 

I was getting 404 for files like config.js, language etc because the urls constructed for them were pointing to my localhost and not the CDN. I finally resolved by adding the following line in settings.py:

`TEXT_CKEDITOR_BASE_PATH = 'https://{}/djangocms_text_ckeditor/ckeditor/'.format(STATIC_URL)
`

The issue is in the use of [urljoin to construct the static URL](https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/settings.py#L35). It works perfectly if you are serving the files from your app but not if you are using a CDN. 

_**I urge you to add this line to the documentation so that others do not face this issue.**_
 
**I suppose this can be fixed by checking what storage is being used and then splitting the URL and replacing the netlock and joining it again but that seems like overkill to me. Perhaps there is an easier solution too.**

Edit:

I can do the needful provided this seems like a workable solution. Please let me know. Thanks!

**Comment by PanchoBubble** [comment]
Thanks mate
