### ISSUE TITLE
EasyImage Plugin Integration

### ISSUE THREAD

**Issue by agajankush** [django-cms/djangocms-text-ckeditor#518]
Can we integrate EasyImage plugin in djangocms_text-ckeditor?

**Comment by agajankush** [comment]
I tried downloading the package from ckeditor site and using that instead of the default one but got some errors which  I am not sure how to debug.

**Comment by jottunn** [comment]
bump

**Comment by jrief** [comment]
with EasyImage you can not use django-filer. Do you really intended this?

**Comment by jottunn** [comment]
I guess my intention is the same as @agajankush,  I don't have the option to upload images with the image plugin in a HTMLField, only option is to provide an image url, so I thought I would give another plugin a try. so this is more related to #https://github.com/divio/djangocms-text-ckeditor/issues/519

**Comment by yakky** [comment]
@jottunn @agajankush you can check https://github.com/nephila/django-ckeditor-filebrowser-filer which integrates filer in plain HTMLField.
Disclaimer: I no longer use it, and its ckeditor plugin code is rather horrible, but it may help cover your use case
