### ISSUE TITLE
Setup image uploader 

### ISSUE THREAD

**Issue by agajankush** [django-cms/djangocms-text-ckeditor#519]
how can i setup image uploader everytime I try to send image to server it throws csrf token error.
Can anyone please please help me with this setup which I think should me simple as it is in ckeditor itself.
Or point to doc which will help me do it.

**Comment by juliendland** [comment]
Hi,
like you I tried to add ckeditor plugin (uploadimage) with it dependencies. First I added ckeditor's plugins in the static folder: `djangocms_text_ckeditor/static/djangocms_text_ckeditor/ckeditor/plugins/`
After in settimgs.py I load extraPlugins and added it to my toolbar_HTMLField like this:
`CKEDITOR_SETTINGS_CUSTOM_BLOG = {
    'language': '{{ language }}',
    'toolbar_HTMLField': [
        {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
        ['Format', 'Styles'],
        ['Bold', 'Italic', 'Underline', '-', 'Subscript', 'Superscript', '-', 'RemoveFormat', 'image'],
        {'name': 'colors', 'items': ['TextColor', 'BGColor']},
        {'name': 'insert', 'items': ['Uploadimage', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak']},
        # {'name': 'forms', 'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton']},
    ],
    'extraPlugins': ','.join([
        'notificationaggregator',
        'dialog',
        'dialogui',
        'clipboard',
        'uploadwidget',
        'notification',
        'uploadimage',
        'lineutils',
        'uploadimage', # the upload image feature
        'widget',
        'lineutils',
        'elementspath'
    ]),
    'removePlugins': 'image',
    'skin': 'moono-lisa',
}`
But the plugin doesn't work so I hope your issue will help us.
