### ISSUE TITLE
Excessive space rendered after plugins returning tags causes comma etc. looks ugly

### ISSUE THREAD

**Issue by sq9mev** [django-cms/djangocms-text-ckeditor#531]
Well, eg. used with djangocms_bootstrap4 Link plugin, an excessive space is rendered.
It looks ugly especially when comma or point is next to the link:

> LinkText ,

Should be:
> LinkText,

I'm not sure if it's djangocms_bootstrap4 issue or djangocms-text-ckeditor, but i think there may be lots of cases when this space is unwanted and cannot be removed, while it may be inserted by editor in Text plugin edit form.

My proposal is to strip spaces in _render_tag(). Pull request will be provided in a moment.

**Comment by jrief** [comment]
Since this is rendered by the `LinkPlugin`, you should try to fix it there. **djangocms-text-ckeditor** isn't responsible for rendering links.
