### ISSUE TITLE
Typo in toolbar_HTMLField: Blockqote instead of Blockquote; no Blockquote button appears in toolbar

### ISSUE THREAD

**Issue by digodude** [django-cms/djangocms-text-ckeditor#554]
In file: /static/djangocms_text_editor/js/cms.ckeditor.js,
definition of toolbar_HTMLField,
there is a typo for button Blockquote, where Blockqote is instead.

Result: no Blockquote button appears in toolbar.

**Comment by jrief** [comment]
will be fixed in 4.0.1
