### ISSUE TITLE
Formatted html by djangocms_text_ckeditor

### ISSUE THREAD

**Issue by LivanAG** [django-cms/djangocms-text-ckeditor#557]
Hi, I'm working on django-cms using the text editor that djangocms_text_ckeditor comes with by default, and I have a problem.

When I write a text plugin, it formats this text in such a way that I do not have a line break.

Sample text:

Quisque semper nunc vitae erat pellentesque, ac placerat arcu consectetur. In venenatis elit ac ultrices convallis. Duis est nisi, tincidunt ac urna sed, cursus blandit lectus. In ullamcorper sit amet ligula ut eleifend. Proin dictumtempor ligula, ac feugiat metus. Sed finibus tortor eu scelerisque scelerisque.Quisque semper nunc vitae erat pellentesque, ac placerat arcu consectetur. In venenatis elit ac ultrices convallis. Duis est nisi, tincidunt ac urna sed, cursus blandit lectus. In ullamcorper sit amet ligula ut eleifend. Proin dictumtempor ligula, ac feugiat metus. Sed finibus tortor eu scelerisque scelerisque.Quisque semper nunc vitae erat pellentesque, ac placerat arcu consectetur. In venenatis elit ac ultrices convallis. Duis est nisi, tincidunt ac urna sed, cursus blandit lectus. In ullamcorper sit amet ligula ut eleifend. Proin dictumtempor ligula, ac feugiat metus. Sed finibus tortor eu scelerisque scelerisque.

This is how this editor formats it when I give it save:

<p>Quisque&nbsp;semper&nbsp;nunc&nbsp;vitae&nbsp;erat&nbsp;pellentesque,&nbsp;ac&nbsp;placerat&nbsp;arcu&nbsp;consectetur.&nbsp;In&nbsp;venenatis&nbsp;elit&nbsp;ac&nbsp;ultrices&nbsp;convallis.&nbsp;Duis&nbsp;est&nbsp;nisi,&nbsp;tincidunt&nbsp;ac&nbsp;urna&nbsp;sed,&nbsp;cursus&nbsp;blandit&nbsp;lectus.&nbsp;In&nbsp;ullamcorper&nbsp;sit&nbsp;amet&nbsp;ligula&nbsp;ut&nbsp;eleifend.&nbsp;Proin&nbsp;dictumtempor&nbsp;ligula,&nbsp;ac&nbsp;feugiat&nbsp;metus.&nbsp;Sed&nbsp;finibus&nbsp;tortor&nbsp;eu&nbsp;scelerisque&nbsp;scelerisque.Quisque&nbsp;semper&nbsp;nunc&nbsp;vitae&nbsp;erat&nbsp;pellentesque,&nbsp;ac&nbsp;placerat&nbsp;arcu&nbsp;consectetur.&nbsp;In&nbsp;venenatis&nbsp;elit&nbsp;ac&nbsp;ultrices&nbsp;convallis.&nbsp;Duis&nbsp;est&nbsp;nisi,&nbsp;tincidunt&nbsp;ac&nbsp;urna&nbsp;sed,&nbsp;cursus&nbsp;blandit&nbsp;lectus.&nbsp;In&nbsp;ullamcorper&nbsp;sit&nbsp;amet&nbsp;ligula&nbsp;ut&nbsp;eleifend.&nbsp;Proin&nbsp;dictumtempor&nbsp;ligula,&nbsp;ac&nbsp;feugiat&nbsp;metus.&nbsp;Sed&nbsp;finibus&nbsp;tortor&nbsp;eu&nbsp;scelerisque&nbsp;scelerisque.Quisque&nbsp;semper&nbsp;nunc&nbsp;vitae&nbsp;erat&nbsp;pellentesque,&nbsp;ac&nbsp;placerat&nbsp;arcu&nbsp;consectetur.&nbsp;In&nbsp;venenatis&nbsp;elit&nbsp;ac&nbsp;ultrices&nbsp;convallis.&nbsp;Duis&nbsp;est&nbsp;nisi,&nbsp;tincidunt&nbsp;ac&nbsp;urna&nbsp;sed,&nbsp;cursus&nbsp;blandit&nbsp;lectus.&nbsp;In&nbsp;ullamcorper&nbsp;sit&nbsp;amet&nbsp;ligula&nbsp;ut&nbsp;eleifend.&nbsp;Proin&nbsp;dictumtempor&nbsp;ligula,&nbsp;ac&nbsp;feugiat&nbsp;metus.&nbsp;Sed&nbsp;finibus&nbsp;tortor&nbsp;eu&nbsp;scelerisque&nbsp;scelerisque.</p>

I have no idea how to solve this, any help would be welcome, thank you !!

**Comment by jrief** [comment]
Ig you click on the button to render the sources, what does it show?

**Comment by LivanAG** [comment]
> If you click on the button to render the sources, what does it show?


Show this

<div>Quisque&nbsp;semper&nbsp;nunc&nbsp;vitae&nbsp;erat&nbsp;pellentesque,&nbsp;ac&nbsp;placerat&nbsp;arcu&nbsp;consectetur.&nbsp;In&nbsp;venenatis&nbsp;elit&nbsp;ac&nbsp;ultrices&nbsp;convallis.&nbsp;Duis&nbsp;est&nbsp;nisi,&nbsp;tincidunt&nbsp;ac&nbsp;urna&nbsp;sed,&nbsp;cursus&nbsp;blandit&nbsp;lectus.&nbsp;In&nbsp;ullamcorper&nbsp;sit&nbsp;amet&nbsp;ligula&nbsp;ut&nbsp;eleifend.&nbsp;Proin&nbsp;dictumtempor&nbsp;ligula,&nbsp;ac&nbsp;feugiat&nbsp;metus.&nbsp;Sed&nbsp;finibus&nbsp;tortor&nbsp;eu&nbsp;scelerisque&nbsp;scelerisque.Quisque&nbsp;semper&nbsp;nunc&nbsp;vitae&nbsp;erat&nbsp;pellentesque,&nbsp;ac&nbsp;placerat&nbsp;arcu&nbsp;consectetur.&nbsp;In&nbsp;venenatis&nbsp;elit&nbsp;ac&nbsp;ultrices&nbsp;convallis.&nbsp;Duis&nbsp;est&nbsp;nisi,&nbsp;tincidunt&nbsp;ac&nbsp;urna&nbsp;sed,&nbsp;cursus&nbsp;blandit&nbsp;lectus.&nbsp;In&nbsp;ullamcorper&nbsp;sit&nbsp;amet&nbsp;ligula&nbsp;ut&nbsp;eleifend.&nbsp;Proin&nbsp;dictumtempor&nbsp;ligula,&nbsp;ac&nbsp;feugiat&nbsp;metus.&nbsp;Sed&nbsp;finibus&nbsp;tortor&nbsp;eu&nbsp;scelerisque&nbsp;scelerisque.Quisque&nbsp;semper&nbsp;nunc&nbsp;vitae&nbsp;erat&nbsp;pellentesque,&nbsp;ac&nbsp;placerat&nbsp;arcu&nbsp;consectetur.&nbsp;In&nbsp;venenatis&nbsp;elit&nbsp;ac&nbsp;ultrices&nbsp;convallis.&nbsp;Duis&nbsp;est&nbsp;nisi,&nbsp;tincidunt&nbsp;ac&nbsp;urna&nbsp;sed,&nbsp;cursus&nbsp;blandit&nbsp;lectus.&nbsp;In&nbsp;ullamcorper&nbsp;sit&nbsp;amet&nbsp;ligula&nbsp;ut&nbsp;eleifend.&nbsp;Proin&nbsp;dictumtempor&nbsp;ligula,&nbsp;ac&nbsp;feugiat&nbsp;metus.&nbsp;Sed&nbsp;finibus&nbsp;tortor&nbsp;eu&nbsp;scelerisque&nbsp;scelerisque.</div>

**Comment by LivanAG** [comment]
Show this

![image](https://user-images.githubusercontent.com/79125230/112575918-a15a7380-8dc7-11eb-80f3-1fb6be97e751.png)

**Comment by LivanAG** [comment]
Solved

It was a version compatibility problem. I reduced it and it works perfectly

**Comment by mateoreyes** [comment]
Hi, what version was that you reduced to solve this problem ?
