### ISSUE TITLE
Mismatch of Widgets.py PATH_TO_JS and the gulp bundle are not checked in the CI tests

### ISSUE THREAD

**Issue by Aiky30** [django-cms/djangocms-text-ckeditor#566]
The gulp bundle command builds a js file and makes an automatic change in the widgets.py file, it's possible to forget to commit / or not see the change needs to be comitted and the ci tests pass on a package that can't actually be used because the widgets.py entry doesn't match the file generated.

A test is required to check that the bundle and the PATH_TO_JS entry in widgets.py match.

**Comment by vinitkumar** [comment]
One good solution to use a pre-commit hook like this:

```sh
#! /bin/bash
#  Optimizations  and tasks running for production
# pre-commit hook to run gulp tasks
jsFile = "{path-to}*..js"
for file in $( exec git diff-index --cached --name-only HEAD )
do
    if [[ $file == *".js"* ]]; then
      containsJsFile=1
    fi
done
if [[ $containsJsFile ]]; then
  echo "Concating and minifying js files.Hold tight"
  gulp js
  git add $jsFile
  # also commit the newly generated bundle files
  git add . 
fi
```

The key here is that whenever it finds that a JS file is changed and is getting committed, the build for gulp gets triggered and if it passes, the file and the gulp generated bundle file is also committed. This will ensure that we don't miss building or committing the code by mistake.
