### ISSUE TITLE
Translation files need update from Transifex

### ISSUE THREAD

**Issue by MacLake** [django-cms/djangocms-text-ckeditor#567]
I wanted to fix a spelling mistake in the German localisation file on Transifex (wrong: Standart Plugins, correct: Standard-Plugins), but I noticed that it has been corrected already two years ago. But that doesn’t help if nobody updates the files here. ;-)

So how is the standard procedure for updating the l10n file from Transifex? If I can help, just tell me!

Jens-Erik

**Comment by goutnet** [comment]
no worries, the translation will get automatically updated by the release script.

**Comment by MacLake** [comment]
Okay, thanks!

**Comment by goutnet** [comment]
can you check on 3.9.0rc1 if those are pulled correctly?

**Comment by goutnet** [comment]
@MacLake  ^?

**Comment by MacLake** [comment]
@goutnet Well, this is another project, and as long as you don’t release a new version of djangocms-text-ckeditor with updated translation strings, we will still have the old ones here. The [l10 files](https://github.com/django-cms/djangocms-text-ckeditor/tree/master/djangocms_text_ckeditor/locale) here are still 2 a old. Or do I misunderstand you?

**Comment by goutnet** [comment]
thanks for mentioning this, indeed. Let me check with @NicolaiRidani  to get sufficient accesses to manage a release here.
