### ISSUE TITLE
Unabable to have google fonts(or any other fonts) on my ckeditor

### ISSUE THREAD

**Issue by olsey** [django-cms/djangocms-text-ckeditor#575]
I have installed djangocms-text-ckeditor>=4.0,<5.0 and after all I tried I still can not make my placeholder texts with fonts or any other advanced style. I have installed it with pip install so I have not a folder where I can add plugins and the configs I have seen do not work.

**Comment by fsbraun** [comment]
#olsey I do not know if this is still current. The way to add fonts and other stylings for that matter is to add an item `contentsCss` to `CKEDITOR_SETTINGS`, e.g.,

    CKEDITOR_SETTINGS = {
        "contentsCss" = "/url_path/to/my.css",
    }
