### ISSUE TITLE
Source view almost unusable due to grey on white colour

### ISSUE THREAD

**Issue by marksweb** [django-cms/djangocms-text-ckeditor#588]
I've certainly seen the source view black on white in the past, but I'm currently getting grey on white which is very difficult to use.

<img width="424" alt="Screenshot 2022-02-24 at 11 20 13" src="https://user-images.githubusercontent.com/1461191/155520421-813d6c40-798f-4ea9-8cf6-d3ad9a06a3f3.png">

I know we can add custom style sheets etc, but this is just a default setup and I don't think we should have to customise to make things more usable.

**Comment by fsbraun** [comment]
Solved with https://github.com/django-cms/djangocms-text-ckeditor/pull/590 :-)
