### ISSUE TITLE
Maintenance of package

### ISSUE THREAD

**Issue by DmytroLitvinov** [django-cms/djangocms-text-ckeditor#589]
Hi guys,
Thank you for that great library for DjangoCMS.

I see you started to deprecate some of your packages  We would appreciate any response regarding the maintenance of that package. Do you plan to support it or it is deprecated and you can mark it as archived?

**Comment by marksweb** [comment]
@DmytroLitvinov hi, this package isn't deprecated. Its not had a release for a while, but it's stable & functional.

**Comment by vinitkumar** [comment]
@DmytroLitvinov This is very much active, we just fixed the CI, please feel free to send a PR for fixes etc. and we will be happy to review and merge.

**Comment by DmytroLitvinov** [comment]
Hi @vinitkumar ,
The one which we need in our project is related to that [PR](https://github.com/django-cms/djangocms-text-ckeditor/pull/532).
Is there any help of review that PR? I am ready to provide a help with that.

**Comment by vinitkumar** [comment]
@DmytroLitvinov I would suggest read through the comments and implement the fix following the comments by @jrief. If all seems good, I will be more than happy to review and merge it.

**Comment by DmytroLitvinov** [comment]
@vinitkumar , thank you for your comment.
Created [PR](https://github.com/django-cms/djangocms-text-ckeditor/pull/597). Could you please review it?

**Comment by DmytroLitvinov** [comment]
Hi @vinitkumar , @marksweb ,

Any plan on releasing new version of `djangocms-text-ckeditor` with fixes which were merged recently? Do you need my help in that process?

**Comment by marksweb** [comment]
@DmytroLitvinov I plan to release 5.0 but just need to spare time to do that.

**Comment by DmytroLitvinov** [comment]
Hey @marksweb ,
Thank you for release :)
