### ISSUE TITLE
Editing HTML in Django CMS with Dark Mode enabled is almost impossible

### ISSUE THREAD

**Issue by mogoh** [django-cms/djangocms-text-ckeditor#607]
Hello.

Trying to edit the HTML of a page with the integrated CKEditor and Dark Mode enabled is basically impossible, because the Text is light gray on white. See screenshot.

![Screenshot 2022-05-06 at 15-31-34 Home - CERES - Ruhr-Universität Bochum](https://user-images.githubusercontent.com/580975/167146078-49bc5153-d952-4940-9b8a-327b936f2301.png)

![Screenshot_20220506_154410](https://user-images.githubusercontent.com/580975/167146096-e718da3e-49a9-42f1-adc5-47ea786ab734.png)

I am reporting this here because it looks like the CSS is inherited from this repository.
If this is the wrong place, please let me know and point me to the right place.

I am using:

- Firefox 99 with dark mode
- Django==3.2.13
- django-cms==3.10.0
- djangocms-admin-style==3.1.1
- djangocms-text-ckeditor==5.0.1

**Comment by fsbraun** [comment]
@mogoh Thanks for reporting this issue. From your screenshots I see that CKEditor does not respect dark mode. Therefore I took the liberty to transfer the issue.

@marksweb I believe the issue will be automatically fixed if we run `gulp build` to patch the css files and release a bugfix 5.0.2.

**Comment by fsbraun** [comment]
@mogoh This issue is fixed in version 5.1. Thanks for pointing it out!

**Comment by mogoh** [comment]
@fsbraun Thank you for fixing!
