### ISSUE TITLE
Toolbar gets garbled after inline editing in django CMS < 3.10

### ISSUE THREAD

**Issue by jgadelange** [django-cms/djangocms-text-ckeditor#620]
When using inline editing in combination with `django-cms==3.9` after completing an inline edit the toolbar gets garbeld. Some buttons dissapear completely and after pushing the toggle button a strange page is shown.

Attached a screencast of the behaviour (there is some style flickering in there as well, that is due to our setup)

https://user-images.githubusercontent.com/432366/174974684-8b190e53-833d-4025-b09b-812dbaa814e4.mov

**Comment by fsbraun** [comment]
This behavior is due to a bug in django-cms < 3.10 which makes the server return a wrong toolbar with invalid links. 

#619 implements a work around forcing a page reload if the installed version of django cms is earlier than 3.10. Will be released in 5.1.1.
