### ISSUE TITLE
Polish letter 'ó' in source mode

### ISSUE THREAD

**Issue by Corvette653** [django-cms/djangocms-text-ckeditor#628]
Hi, I've found a bug.
All polish letters display as they should both in classic and source mode except for `ó` which changes into `&oacute;`.
That's all, just some small oversight :)

**Comment by fsbraun** [comment]
What's the difference between ó and ó? I do not know Polish, but to me both look quite similar. Do you have the unicodes of these two letters? If I type ó into ckeditor it is converted to `&oacute;`. Would that be incorrect for the Polish language?

**Comment by Corvette653** [comment]
I'm sorry, github translated html code into actual letter.
You're right, that's exactly the same letter and `&oacute;` is a correct code for `ó`.
And once again you're right - I wanted to avoid translating letter into code, your advice helped.

Now I know the bug is a bit different.
In Polish language there are 9 special letters: `ą, ć, ę, ł, ń, ó, ś, ź, ż` and `ó` is the only one which is translated into it's code.
![polish_letters](https://user-images.githubusercontent.com/56157995/189181820-14c59b1e-9243-4968-bca1-e5b0b55fa6ed.png)

Once more thank for your help, "entities_latin" is everything I personally needed

**Comment by fsbraun** [comment]
Great! Pleasure to help!
