### ISSUE TITLE
Issues when using HTMLField not in full-screen mode - link dialogue not positioned correctly

### ISSUE THREAD

**Issue by petrklus** [django-cms/djangocms-text-ckeditor#630]
Steps to reproduce:
- Open Text plugin or any other custom plugin using HTMLField
- (if using Text plugin) exit the full-screen mode
- Open link dialogue

The issue is further exacerbated in custom plugins where the HTMLField is not at the top, as it forces the whole plugin iframe to scroll to the top when the link dialogue is activated, scrolling the HTMLField that is being interacted with out of view.

https://user-images.githubusercontent.com/1115667/192570444-93575fc1-51e9-4535-9476-5932d774ef6b.mov

Reproduced on Divio with clean Django CMS install and following package versions:
![image](https://user-images.githubusercontent.com/1115667/192570700-7c7116f7-6349-4523-bc04-aa359e3e6266.png)

**Comment by petrklus** [comment]
Can we re-open this one? Still an issue.

**Comment by petrklus** [comment]
@fsbraun can we please re-open this issue? Still the same problem.

**Comment by fsbraun** [comment]
Since I cannot reproduce the situation where the ckeditor dialogue scrolls an iframe to the top, can you share a demonstration of that?

**Comment by petrklus** [comment]
@fsbraun here it can be seen a bit better:
https://user-images.githubusercontent.com/1115667/220878351-30a172ab-5eb4-4c69-9c95-b765fb8ae799.mov

You can see that the link dialogue does not centre unless it's repositioned. This is a new bug after upgrading to 5.x, it was not an issue with 3.9.1

**Comment by fsbraun** [comment]
@petrklus Link's broken :-(

**Comment by fsbraun** [comment]
@petrklus OK, now I can see what happens. Can you for testing purpose replace the file `djangocms-text-ckeditor/djangocms_text_ckeditor/static/djangocms_text_ckeditor/ckeditor_plugins/cmsdialog/plugin.js` with [this version](https://github.com/django-cms/djangocms-text-ckeditor/blob/3.9.1/djangocms_text_ckeditor/static/djangocms_text_ckeditor/ckeditor_plugins/cmsdialog/plugin.js)?

If this does not change anything, I assume it must be the ckeditor version. It used to be 4.7 or so and is at 4.17 now?
