### ISSUE TITLE
add tel hyperlinks not working

### ISSUE THREAD

**Issue by i-salameh95** [django-cms/djangocms-text-ckeditor#638]
Hello, 
I have noticed that adding telephone links inside djangocms-text-ckeditor is wrapping the output link:
for example:
```
<span class="pbmit-footer-contact-info-wrap"><span class="pbmit-label pbmit-label-1">contact by phone:</span>
<a href="tel: 0097092331471"> +97092331471</a></span>

```
Then the outputed link appear without href at all. 
this happened with tel link only.
djangocms-text-ckeditor version used: 5.1.1
django cms version: 3.11

**Comment by fsbraun** [comment]
This is a bug of the html sanitizer. It needs rework anyway. For the time being. I'd suggest to use a Link plugin (e.g., djangocms-frontend's) and enter the phone link. This will render correctly.

**Comment by petrklus** [comment]
@fsbraun @i-salameh95 there is also another fix - you can put `TEXT_ADDITIONAL_PROTOCOLS` setting into your settings.py and add the missing protocol. 

This line fixed the issue for me:

```
TEXT_ADDITIONAL_PROTOCOLS = ["tel"]
```

**Comment by petrklus** [comment]
Any thoughts on the above? Perhaps the tel protocol should be added by default?
