### ISSUE TITLE
create_picture_plugin incompatible with djangocms-picture 2+

### ISSUE THREAD

**Issue by leture** [django-cms/djangocms-text-ckeditor#642]
Hi,

according to https://github.com/django-cms/djangocms-picture/blob/master/CHANGELOG.rst#200-2016-09-08 djangocms-picture (specifically "Migrate model field image to FilerImageField and renamed to picture") I assume the current `create_picture_plugin` implementation does not work properly with djangocms-picture 2.0.0 or higher.

The current implementation sets `pic.image = path` but would need to set `pic.picture = some_FilerImage_instance` I assume. Do I miss something here or is my observation valid? If my observation is valid, is there interest in fixing this? If so I would create a pull request then.

Greetings

**Comment by fsbraun** [comment]
It would be great if you could fix that issue!

**Comment by fsbraun** [comment]
@leture Can I still interest you in crating this Pull Request? Would be awesome!

**Comment by leture** [comment]
@fsbraun Sorry for the delay but I finally found the time to do it :-)
