### ISSUE TITLE
Inline editing possible on extended plugins?

### ISSUE THREAD

**Issue by imagescape** [django-cms/djangocms-text-ckeditor#646]
I noticed an issue where my plugins subclassing TextPlugin were not rendering the correct template in edit mode. Eventually realized this was due to the conditional in this [get_render_template](https://github.com/django-cms/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/cms_plugins.py#L540) method. The plugins render with the inline.html template even without TEXT_INLINE_EDITING = True. 

Seems that a fix may be needed for that template conditional but I decided to just try enabling inline editing and make my own inline template version for the custom plugin following the same structure as the template here:
https://github.com/django-cms/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/templates/cms/plugins/inline.html

This doesn't seem to work, however. Inline editing is there for standard text plugins but not my extended plugins. Is there something else needed to get this working?

Using:
django-cms 3.11.3
djangocms-text-ckeditor 5.1.2

**Comment by fsbraun** [comment]
Your approach seems reasonable to me. Can you share what goes wrong?

**Comment by imagescape** [comment]
@fsbraun Inline editing is not present for those extended plugins. One thing I've noticed is a conditional in the [js explicitly checks](https://github.com/django-cms/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/static/djangocms_text_ckeditor/js/cms.ckeditor.js#L130) for plugin type TextPlugin which would explain at least that portion of it being missing. 

Would love to get it working for those but could be that it's just not feasible to add inline editing to extended plugins (or plugins that use HTMLField). In that case, may just need to adjust the conditional I mentioned above in get_render_template to only return self.inline_editing_template when plugin type is TextPlugin and TEXT_INLINE_EDITING=True.

**Comment by fsbraun** [comment]
Your analysis makes sense. The JS side does not know about plugin inheritance and can only make decisions on plugin names.

**Comment by imagescape** [comment]
@fsbraun Definitely. I was experimenting with hard-coding the name of my custom plugin in the javascript and it actually works as far as editing and saving though it's buggy as it's wrapping all the fields in the editor as opposed to just the one using ckeditor. I can see that identifying and targeting just the ckeditor field could be a challenge. Let me know any way I can assist.

**Comment by imagescape** [comment]
Thinking about how one might identify which fields should be inline-editable, I don't think it would be unreasonable to require some kind of additional configuration within a custom plugin's inline_editing_template. Just one thought.

**Comment by joshyu** [comment]
@fsbraun , do we have any solution for this feature on extended plugin?
