### ISSUE TITLE
[BUG] Setting `ALLOW_TOKEN_PARSERS` is not extended

### ISSUE THREAD

**Issue by DmytroLitvinov** [django-cms/djangocms-text-ckeditor#647]
According to documentation, it says that I can provide custom token parsers via settings ALLOW_TOKEN_PARSERS

If we check source code https://github.com/django-cms/djangocms-text-ckeditor/blob/50bc9c1c8d14a7a9f3eb9a9620a39a0e25ec8923/djangocms_text_ckeditor/settings.py#L39 we can see it is hardcoded and not updated via `django.conf.settings`.

My proposal is to add something like next:
```
ALLOW_TOKEN_PARSERS = [
  'djangocms_text_ckeditor.attribute_parsers.DataAttributeParser',
  *getattr(settings, 'ALLOW_TOKEN_PARSERS', []),
]
```

**Comment by fsbraun** [comment]
@DmytroLitvinov Can I interest you in creating a PR?
