### ISSUE TITLE
Deprecation warning for plugin Flash

### ISSUE THREAD

**Issue by jrief** [django-cms/djangocms-text-ckeditor#655]
Whenever I open a text-ckeditor plugin, I get this deprecation warning:

![Screenshot 2023-10-13 at 08 54 38](https://github.com/django-cms/djangocms-text-ckeditor/assets/1132472/6f2e3757-e886-458f-9187-7887a4a99230)

I know, @fsbraun disabled "flash" in 31cb918c4a7dede92027a695e77ae5b0b8f818ff , so it seems strange that it still is in use. It seems that it has to be removed from [here](https://github.com/django-cms/djangocms-text-ckeditor/blob/9ef7a2a43564e4c989140ce885f833965c2ab382/djangocms_text_ckeditor/static/djangocms_text_ckeditor/ckeditor/ckeditor.js#L1291C415-L1291C415), which is a file beyond our control.

**Comment by fsbraun** [comment]
I agree. It's an artefact from using Ckeditor 4. It could (only) be removed by patching Ckeditor 4.

**Comment by MacLake** [comment]
No, you can also remove the Flash plug-in in the config. While defining the set of buttons doesn’t seem to help, using `'removePlugins'` does the trick. I just learnt that from Vinit’s answer in the Slack support channel when I asked how to get rid of Word formatting. So here are my settings:

```python
CKEDITOR_SETTINGS: dict[str, Union[str, list]] = {
    'removePlugins':
        ['pastefromword', 'flash'],
    'pasteFilter':
        "p b i u h1 h2 h3 h4 h5 h6 ul ol li; table tr td sub sup; a[href]",
    'stylesSet': 'default:/static/js/addons/ckeditor.wysiwyg.js',
    'contentsCss': ['/static/semantic/semantic.min.css'],
}
```

**Comment by MacLake** [comment]
I’ve added it to the default config: 
https://github.com/django-cms/djangocms-text-ckeditor/pull/656
