### ISSUE TITLE
HTMLField in Django InlineAdmin causes TypeError when adding new record

### ISSUE THREAD

**Issue by lab360-ch** [django-cms/djangocms-text-ckeditor#657]
I have a Model with an HTMLField in it. The Model with the HTMLField is used as StackedInline in the Django Admin.

When I add a new record, the CKEditor is not shown, instead only the Textarea is displayed, and I got a JavaScript Error: `TypeError: Cannot read properties of undefined (reading 'replace')`.

![image](https://github.com/django-cms/djangocms-text-ckeditor/assets/38225706/827f80cb-13ba-4a77-a9e1-16662903bc89)

The model Looks like this:

```python
class CategoryTextSlide(models.Model):
    category = models.ForeignKey(
        Category,
        related_name="slides",
        verbose_name="Kategorie",
        on_delete=models.CASCADE,
    )

    text = HTMLField(
        verbose_name="Text",
        configuration="CKEDITOR_CATEGORY_TEASER_SLIDE_SETTINGS",
    )

    class Meta:
        verbose_name = "Kategorie Text Slide"
        verbose_name_plural = "Kategorien Text Slides"
```

The CKEditor settings like this:

```python
CKEDITOR_CATEGORY_TEASER_SLIDE_SETTINGS = {
    "bodyClass": "category-teaser-slide",
    "toolbar_HTMLField": [
        ["Undo", "Redo"],
        ["Format", "RemoveFormat", "Bold", "Link"],
        ["Source", "Maximize"],
    ],
    "contentsCss": "/static/ckeditor.css",
    "format_tags": "h3;p",
}
```

And the Admin config like this:

```python
class CategoryTextSlideAdmin(admin.StackedInline):
    model = CategoryTextSlide
    min_num = 1
    extra = 0
```

I use the following version:

- Django: 4.25
- Django CMS: 3.11.4
- Django CMS CKEditor: 5.1.4
- Python: 3.11.4

Thanks for helping.

Best regards

**Comment by marksweb** [comment]
This looks like you'd need to add custom javascript to instantiate a new ckeditor when you add a new inline.

This maybe considered outside of the scope of the plugin though as I'm not clear on how you're using it. This seems like regular Django.
