### ISSUE TITLE
TextPlugin removes source code HTML on save

### ISSUE THREAD

**Issue by Noah3141** [django-cms/djangocms-text-ckeditor#667]
I have had something similar occur in two separate projects.

In one, I was making modifications to the source HTML, like adding another style attribute to a tag, and my new attribute would be gone on save, leaving only the previous state of the tag.

In the current one, all tag attributes are getting purged on TextPlugin save. 

In both these cases the TextPlugins were created within placeholder fields in the following manner:
```python
block_text_plugin: TextPlugin = add_plugin(
    placeholder=subsection_placeholder,
    plugin_type=text_plugin,
    language="en-us",
    target=block_plugin,
    body=block["body"],
)
```

Where `block['body']` contains HTML elements, including some `<ol style="list-style-type:lower-alpha">`.

Before: `<ol style="list-style-type:lower-roman">`
After: `<ol>`

djangocms-text-ckeditor 5.1.5

**Comment by fsbraun** [comment]
djangocms-text-ckeditor sanitizes any HTML before safe. You might need to configure the sanitizer. See here: https://github.com/django-cms/djangocms-text-ckeditor#configurable-sanitizer

**Comment by Noah3141** [comment]
It seems like it would certainly be the root cause, but I can't seem to get the settings to take effect:

I managed to get the Global setting to turn it off altogether to work, but I suspect I want a bit more precision.
Specifically providing "style" inside the settings.py did not preserve the style attributes.

So, now I'm trying the custom parser. I have it successfully hooked up, because I can see its print statements when made within the parse function

```python
from djangocms_text_ckeditor.sanitizer import AllowTokenParser


Keep = bool
class ListAttributeParser(AllowTokenParser):
    def parse(self, attribute: str, val: str) -> Keep:
        if attribute == "style": 
            print(val) # -->  list-style-type:lower-roman
            return True
        else: return False
 ```
 I did add: 
    'basicEntities': False,
    'entities': False,

**Comment by fsbraun** [comment]
Have you tried `TEXT_ADDITIONAL_ATTRIBUTES = ("style",)`?

**Comment by fsbraun** [comment]
Does it work? I must say, I am not an expert of `htmllib`.

**Comment by Noah3141** [comment]
I have not gotten the custom parser to work, no. Switching True/False with each other didn't seem to have an effect.
