### ISSUE TITLE
Fix update notification on latest foss version of ckeditor 4.22.*.

### ISSUE THREAD

**Issue by corentinbettiol** [django-cms/djangocms-text-ckeditor#668]
Hi. Ckeditor started to show a notification yesterday:
![image](https://github.com/django-cms/djangocms-text-ckeditor/assets/45763865/ef842d93-cd94-411e-a0bd-7724d88ad60a)

It's a problem because it shows on every ckeditor box, even the ones who are part of a form on a public-facing website: every visitor of the site will see this.

![image](https://github.com/django-cms/djangocms-text-ckeditor/assets/45763865/1e5c71a5-f5e7-43da-9436-d8d494d2383e)

Since we can't use versions 4.23+ (those are lts versions, which needs a license key to work, they changed the license), what we can do as a temporary fix is simply remove the notification process on the ckeditor code (gnu gpl3, we're allowed to make changes to the program).

**Comment by fsbraun** [comment]
@matthiask Thank you very much for the hint!! I like the system check warning.

**Comment by corentinbettiol** [comment]
Thank you for this fix @matthiask!
