### ISSUE TITLE
BUG - Color Popup "OK" Button/dialog closes table cell popup/dialog

### ISSUE THREAD

**Issue by s4ke** [django-cms/djangocms-text-ckeditor#672]
We use the editor in a page that has tables in it. When we want to change the background color of a cell, we go to the cell settings:

![grafik](https://github.com/django-cms/djangocms-text-ckeditor/assets/719760/aafd90a3-ebf9-40df-a090-a31bb7d1365c)

then, we click on background color:

![grafik](https://github.com/django-cms/djangocms-text-ckeditor/assets/719760/79785942-fc58-4d2e-80ce-c92813207d37)

select color, click on OK.

Cell editor is gone and page has a gray overlay and we can't edit anymore:

![grafik](https://github.com/django-cms/djangocms-text-ckeditor/assets/719760/ea0619fc-f19e-4cb0-ac1e-a0dc8728fc6f)

My hunch says that there is something wired up weirdly either in our app, or in one of the recentupdates of this package that causes the second popup to close all existing popups. Would be awesome, if you could give us some pointers how we could improve this situation.

We are on the latest version of djangocms-text-ckeditor (5.1.5).

**Comment by fsbraun** [comment]
How do you get to cell settings?

**Comment by s4ke** [comment]
we right click on a cell:

![grafik](https://github.com/django-cms/djangocms-text-ckeditor/assets/719760/d81130f6-4253-473a-b28b-960d16b9ba62)

**Comment by fsbraun** [comment]
Are you using the bundled version of ckeditor? I do not have this menu entry. Not sure why.

**Comment by s4ke** [comment]
We are using the bundled version as far as I can tell. This is our CKEDITOR_SETTINGS config:

```python
CKEDITOR_SETTINGS = {
    'language': '{{ language }}',
    'skin': 'moono',
    'toolbar_CMS': [
        ['Undo', 'Redo'],
        ['cmsplugins', 'cmswidget', '-', 'ShowBlocks'],
        ['Format', 'Styles'],
        ['TextColor', 'BGColor', '-', 'PasteText', 'PasteFromWord', '-', 'Scayt'],
        ['Find', 'Replace'],
        ['Maximize', ''],
        '/',
        ['FontSize', 'Bold', 'Italic', 'Underline', '-', 'Subscript', 'Superscript', '-', 'CopyFormatting', 'RemoveFormat', '-', 'SpecialChar','Image'],
        ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
        ['HorizontalRule'],
        ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'Table','AddLayout'],
        ['Source'],
    ],
    'toolbar_HTMLField': [
        ['Undo', 'Redo'],
        ['ShowBlocks'],
        ['Format', 'Styles'],
        ['TextColor', 'BGColor', '-', 'PasteText', 'PasteFromWord', '-', 'Scayt'],
        ['Find', 'Replace'],
        ['Maximize', ''],
        '/',
        ['FontSize', 'Bold', 'Italic', 'Underline', '-', 'Subscript', 'Superscript', '-', 'CopyFormatting', 'RemoveFormat', '-', 'SpecialChar','Image'],
        ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
        ['HorizontalRule'],
        ['Link', 'Unlink'],
        ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'Table','AddLayout'],
        ['Source'],
    ],
    'extraPlugins': 'wordcount,notification,layoutmanager,dialogadvtab,colordialog,table,tabletools,tableresize,tableselection',
    'layoutmanager_loadbootstrap': True,
    'scayt_autoStartup': True,
    'scayt_sLang': 'de_DE',
    'fontSize_sizes': "Extra klein/1.2rem;Klein/1.5rem;Normal/1.8rem;Gross/2.1rem;Extra gross/2.4rem;",
}
```

**Comment by fsbraun** [comment]
Yes, it seems. They're not part of the bundled ckeditor. I cannot judge if the issue is in the table tools. There also might be some side effect with the `cmsdialog` plugin which comes with djangocms-text-ckeditor. Do you see any change if you add `removePlugins: "cmsdialog"` to the `CKEDITOR_SETTINGS`? I am not sure this is sufficient to keep the cmsdialog from loading. You might want to check the browser's network history.
