### ISSUE TITLE
Height of Color Panel too small

### ISSUE THREAD

**Issue by SteveGZr** [django-cms/djangocms-text-ckeditor#673]
I updated my djangocms-text-editor version from 4 to 5 a few months ago. I am now using the current version 5.1.5.

Now I have noticed that the dialogue for the colour selection is no longer displayed correctly. At first I thought it was a misconfiguration on my site, but I have now tried the default settings and found that the height of the dialogue is no longer sufficient.
This causes content to be cut off.

As you can see in the following screenshots, the height is overwritten by a value with `auto !important`. If this is not set, the content is displayed correctly.

![screen](https://github.com/django-cms/djangocms-text-ckeditor/assets/12197139/b3ef5cb4-3547-4e8e-8038-3ce2e5b54177)

**Comment by fsbraun** [comment]
@SteveGZr Thanks for reporting this!
