### ISSUE TITLE
Double clicking an inserted link doesn't opens the edit popup in the latest version

### ISSUE THREAD

**Issue by vipulnarang95** [django-cms/djangocms-text-ckeditor#675]
If you have added a link in the editor and if you try to edit it by double clicking. The edit popup of link doesn't appears. Please confirm, it was working fine until we upgraded to 5.1.5 version

**Comment by fsbraun** [comment]
Sorry, I cannot reproduce. Can you give a more specific description? Text-enabled plugins work fine for me, both when editing inline and from the change plugin modal.

**Comment by vipulnarang95** [comment]
> Sorry, I cannot reproduce. Can you give a more specific description? Text-enabled plugins work fine for me, both when editing inline and from the change plugin modal.

If you check the link which is an inbuilt inline which doesn't come under the CMS plugins. Can you check this once ![image](https://github.com/user-attachments/assets/93b166f6-a44a-4b95-ae15-26d54c6dd064)

In the image the blue text is a normal link which is highlighted from the mouse hover. When we double click on this blue text the editor doesn't pops up but comes when we right click on the blue text and click edit
Earlier on double clicking the blue text opens the link popup

It is happening for cms text enabled plugins but not this link.

**Comment by fsbraun** [comment]
OK, now I understand. I can confirm the behaviour. 

Will need to take a look to identify the source of the behavior.

**Comment by vipulnarang95** [comment]
Thanks @fsbraun. Please keep us updated thanks.

**Comment by vipulnarang95** [comment]
I can confirm it started working now.

**Comment by vipulnarang95** [comment]
@fsbraun I have one more question around the html field. If we use the html field and need CMS plugins over there. Can it be possible in any way.

I checked the TextPlugin implementation which implements a Texteditor widget in which plugins are initialised using get_plugins method.

Is there a way we can give the text enabled plugins inside the htmlfield?

**Comment by fsbraun** [comment]
No.

**Comment by vipulnarang95** [comment]
@fsbraun Can we have this released?
